[Hotkeys]
# 1=Analog Up
1=KEY_RIGHTBRACE
# 2=Analog Down
2=KEY_3
# 3=Analog Left
3=KEY_2
# 4=Analog Right
4=KEY_4
# 5=ModX
5=KEY_V
# 6=ModY
6=KEY_B
# 7=A
7=KEY_M
# 8=B
8=KEY_O
# 9=L
9=KEY_Q
# 10=R
10=KEY_9
# 11=X
11=KEY_P
# 12=Y
12=KEY_0
# 13=Z
13=KEY_LEFTBRACE
# 14=C-Up
14=KEY_K
# 15=C-Down
15=KEY_SPACE
# 16=C-Left
16=KEY_N
# 17=C-Right
17=KEY_COMMA
# 18=Light Shield
18=KEY_MINUS
# 19=Mid Shield
19=KEY_EQUAL
# 20=Start
20=KEY_7
# 21=D-Up
21=KEY_UP
# 22=D-Down
22=KEY_DOWN
# 23=D-Left
23=KEY_LEFT
# 24=D-Right
24=KEY_RIGHT
